---
-
  hosts: all
  tasks:
   - name: AllowSSH
    
     iptables:

         chain: INPUT
         comment: " Accept new SSH connection"
         ctstate: NEW
         destination_port: 22
         jump: ACCEPT
         protocol: tcp


   - name: Allow HTTP
     iptables:

         chain: INPUT
         comment: "Accept new HTTPS connection"
         ctstate: NEW
         destination_port: 8006
         jump: ACCEPT
         protocol: tcp     
